# Задачи по Pandas (часть 1).

**Нужно решить все задачи.**

# Для облегчения процесса проверки задач прошу размещать все указанные файлы исключительно в сессионном хранилище Colab, чтобы доступ к ним был доступен без указания полного адреса, и считывать их в указанные переменные.

In [2]:
# Считайте данные из файлов, сохраните их в переменные соответствующие переменные
import pandas as pd

df_p = pd.read_csv("Products.csv", sep=';') # для Products
df_c = pd.read_csv("Customers.csv", sep=';') # для Customers
df_o = pd.read_csv("Orders.csv", sep=';')  # для Orders
df_od = pd.read_csv("Order_details.csv", sep=';') # для Order_details
df_e = pd.read_excel("Employees.xlsx") # для Employees

In [4]:
#по данным из файла Customers
выведите первые 25 строк датафрейма. Как зовут клиента, расположившегося на 25-й строке?
посчитайте количество клиентов, чья должность - Owner. #17

SyntaxError: invalid syntax (1911934800.py, line 3)

In [2]:
display(df_c.head(25))
display(df_c.iloc[24]['ContactName'])
display(df_c[df_c['ContactTitle'] == 'Owner'].shape[0])

,CustomerID,ContactName,ContactTitle,Phone,Address
0,ALFKI,Maria Anders,Sales Representative,030-0074321,Obere Str. 57
1,ANATR,Ana Trujillo,Owner,(5) 555-4729,Avda. de la Constitucion 2222
2,ANTON,Antonio Moreno,Owner,(5) 555-3932,Mataderos 2312
3,AROUT,Thomas Hardy,Sales Representative,(171) 555-7788,120 Hanover Sq.
4,BERGS,Christina Berglund,Order Administrator,0921-12 34 65,Berguvsv?gen 8
5,BLAUS,Hanna Moos,Sales Representative,0621-08460,Forsterstr. 57
6,BLONP,Frederique Citeaux,Marketing Manager,88.60.15.31,"24, place Kleber"
7,BOLID,Martin Sommer,Owner,(91) 555 22 82,"C/ Araquil, 67"
8,BONAP,Laurence Lebihan,Owner,91.24.45.40,"12, rue des Bouchers"
9,BOTTM,Elizabeth Lincoln,Accounting Manager,(604) 555-4729,23 Tsawassen Blvd.
10,BSBEV,Victoria Ashworth,Sales Representative,(171) 555-1212,Fauntleroy Circus
11,CACTU,Patricio Simpson,Sales Agent,(1) 135-5555,Cerrito 333
12,CENTC,Francisco Chang,Marketing Manager,(5) 555-3392,Sierras de Granada 9993
13,CHOPS,Yang Wang,Owner,0452-076545,Hauptstr. 29
14,COMMI,Pedro Afonso,Sales Associate,(11) 555-7647,"Av. dos Lusiadas, 23"
15,CONSH,Elizabeth Brown,Sales Representative,(171) 555-2282,Berkeley Gardens 12 Brewery
16,DRACD,Sven Ottlieb,Order Administrator,0241-039123,Walserweg 21
17,DUMON,Janine Labrune,Owner,40.67.88.88,"67, rue des Cinquante Otages"
18,EASTC,Ann Devon,Sales Agent,(171) 555-0297,35 King George
19,ERNSH,Roland Mendel,Sales Manager,7675-3425,Kirchgasse 6
20,FAMIA,Aria Cruz,Marketing Assistant,(11) 555-9857,"Rua Oros, 92"
21,FISSA,Diego Roel,Accounting Manager,(91) 555 94 44,"C/ Moralzarzal, 86"
22,FOLIG,Martine Rance,Assistant Sales Agent,20.16.10.16,"184, chaussee de Tournai"
23,FOLKO,Maria Larsson,Owner,0695-34 67 21,Akergatan 24
24,FRANK,Peter Franken,Marketing Manager,089-0877310,Berliner Platz 43

'Peter Franken'

17

In [ ]:
#по данным из файла Orders
посчитайте количество заказов, оформленных позднее даты 1997-07-05.  #488
посчитайте количество заказов, вес которых меньше или равен 10.98.   #184

In [3]:
display(df_o[df_o['OrderDate'] > '1997-07-05'].shape[0])
display(df_o[df_o['Freight'] <= 10.98].shape[0])

488

184

In [ ]:
#по данным из файла Customers
Посчитайте количество клиентов, чьи должности входят в список
['Sales Representative','Sales Agent','Sales Associate','Sales Manager','Assistant Sales Agent', 'Assistant Sales Representative']. #43

In [5]:
display(df_c[df_c['ContactTitle'].isin(['Sales Representative','Sales Agent','Sales Associate','Sales Manager','Assistant Sales Agent', 'Assistant Sales Representative'])].shape[0])

43

In [4]:
#по данным из файла Products
Посчитайте количество товаров, которые находятся в диапазоне цен от 18 до 22. Товары стоимостью 18 или 22 тоже должны быть учтены. #16

SyntaxError: invalid syntax (514646627.py, line 2)

In [6]:
display(df_p[(df_p['UnitPrice'] >= 18) & (df_p['UnitPrice'] <= 22)].shape[0])

16

In [ ]:
#по данным из файла Orders
Выведите заказы с весом более 500, которые были оформлены в 1997 году. Сколько их? #5

In [ ]:
df_o['OrderDate'] = pd.to_datetime(df_o['OrderDate'])
df_freight_1997 = df_o[(df_o['OrderDate'].dt.year == 1997) & (df_o['Freight'] > 500)]

display(df_freight_1997)
df_freight_1997.shape[0]

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
231,10479,RATTC,3,1997-03-19,1997-04-16 00:00:00.000,1997-03-21 00:00:00.000,708.95
266,10514,ERNSH,3,1997-04-22,1997-05-20 00:00:00.000,1997-05-16 00:00:00.000,789.95
292,10540,QUICK,3,1997-05-19,1997-06-16 00:00:00.000,1997-06-13 00:00:00.000,1007.64
364,10612,SAVEA,1,1997-07-28,1997-08-25 00:00:00.000,1997-08-01 00:00:00.000,544.08
443,10691,QUICK,2,1997-10-03,1997-11-14 00:00:00.000,1997-10-22 00:00:00.000,810.05

5

In [ ]:
#по данным из файла Orders
Выведите в одной таблице заказы, которые:
- были оформлены в 1997 году;
- заказы с весом более 500.
Сколько их? #416

In [ ]:
display(df_o[(df_o['OrderDate'].dt.year == 1997) | (df_o['Freight'] > 500)])

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
124,10372,QUEEN,5,1996-12-04,1997-01-01 00:00:00.000,1996-12-09 00:00:00.000,890.78
152,10400,EASTC,1,1997-01-01,1997-01-29 00:00:00.000,1997-01-16 00:00:00.000,83.93
153,10401,RATTC,1,1997-01-01,1997-01-29 00:00:00.000,1997-01-10 00:00:00.000,12.51
154,10402,ERNSH,8,1997-01-02,1997-02-13 00:00:00.000,1997-01-10 00:00:00.000,67.88
155,10403,ERNSH,4,1997-01-03,1997-01-31 00:00:00.000,1997-01-09 00:00:00.000,73.79
...,...,...,...,...,...,...,...
664,10912,HUNGO,2,1998-02-26,1998-03-26 00:00:00.000,1998-03-18 00:00:00.000,580.91
735,10983,SAVEA,2,1998-03-27,1998-04-24 00:00:00.000,1998-04-06 00:00:00.000,657.54
769,11017,ERNSH,9,1998-04-13,1998-05-11 00:00:00.000,1998-04-20 00:00:00.000,754.26
782,11030,SAVEA,7,1998-04-17,1998-05-15 00:00:00.000,1998-04-27 00:00:00.000,830.75
784,11032,WHITC,2,1998-04-17,1998-05-15 00:00:00.000,1998-04-23 00:00:00.000,606.19

In [ ]:
#по данным из файла Customers
С помощью метода .str.startswith() .str.startswith()посчитайте количество клиентов, чьи имена начинаются на латинскую букву A. Сколько таких клиентов? #10
Выведите клиентов, чьи номера телефонов содержат 5555 (четыре символа 5 подряд). Четыре пятерки подряд могут быть в начале номера, в середине или в конце. Сколько таких клиентов? #2

In [ ]:
display(df_c[df_c['ContactName'].str.startswith('A')].shape[0])
display(df_c[df_c['Phone'].str.contains('5555')].shape[0])

10

2

In [ ]:
#по данным из файла Orders
Выведите заказы, которые были оформлены в 1997 году. Затем отсортируйте заказы по весу в порядке убывания. Какой заказ OrderID имеет самый большой вес? #10540
Выведите заказы, совершенные в 1997 году. Отсортируйте заказы в порядке возрастания по двум столбцам: ID клиента и вес заказа. Укажите минимальный вес заказа, который совершил клиент с ID ANTON. #4,03

In [ ]:
display(df_o[((df_o['OrderDate'].dt.year == 1997))].sort_values(by='Freight', ascending=False).head(1))

,OrderID,CustomerID,EmployeeID,OrderDate,RequiredDate,ShippedDate,Freight
292,10540,QUICK,3,1997-05-19,1997-06-16 00:00:00.000,1997-06-13 00:00:00.000,1007.64

In [ ]:
#по данным из файла Customers
Посчитайте количество клиентов, у которых должность Owner или Sales Representative. Используйте метод .count(). Сколько таких клиентов? #34

In [8]:
display(df_c[df_c['ContactTitle'].isin(['Owner','Sales Representative'])].count())

CustomerID      34
ContactName     34
ContactTitle    34
Phone           34
Address         34
dtype: int64

In [ ]:
#по данным из файла Orders
Посчитайте разницу между максимальным весом заказа и минимальным весом заказа. Для расчета минимума и максимума используйте агрегирующие функции. #1007,62

In [7]:
print(df_o['Freight'].max() - df_o['Freight'].min())

1007.62

In [ ]:
#по данным из файла Orders
Посчитайте суммарный вес заказов, которые были совершены 26 февраля 1998 года. #776,27

In [44]:
df_o['OrderDate'] = pd.to_datetime(df_o['OrderDate'])
print(df_o[df_o['OrderDate'].dt.date == pd.to_datetime('1998-02-26').date()]['Freight'].sum())

776.27

In [ ]:
#по данным из файла Customers
Посчитайте в разрезе должностей количество клиентов. Иными словами сгруппируйте должности и посчитайте количество клиентов.

In [47]:
display(df_c.groupby('ContactTitle')['CustomerID'].count())

ContactTitle
Accounting Manager                10
Assistant Sales Agent              2
Assistant Sales Representative     1
Marketing Assistant                6
Marketing Manager                 12
Order Administrator                2
Owner                             17
Owner/Marketing Assistant          1
Sales Agent                        5
Sales Associate                    7
Sales Manager                     11
Sales Representative              17
Name: CustomerID, dtype: int64

In [ ]:
#по данным из файла Orders
Посчитайте в разрезе каждого сотрудника EmployeeID количество оформленных заказов. Какой сотрудник оформил меньше всего заказов? #EmployeeID = 5

In [50]:
print(df_o.groupby('EmployeeID')['OrderID'].count().idxmin())

5

In [ ]:
#по данным из файла Orders
В разрезе дат оформления заказов посчитайте количество заказов. В какую дату было оформлено максимальное количество заказов? #1998-02-26

In [57]:
print(df_o.groupby(df_o['OrderDate'].dt.date)['OrderID'].count().idxmax())

1998-02-26

In [ ]:
#по данным из файла Orders
Посчитайте количество заказов в разрезе сотрудников EmployeeID и клиентов CustomerID. Какое максимальное количество заказов оформил один сотрудник одному клиенту? #6

In [ ]:
#по данным из файла Order_details
Сначала рассчитайте для каждой строки датафрейма df_od фактическую скидку и чистую выручку.
Затем посчитайте фактическую скидку и чистую выручку по каждому заказу OrderID. У скольких заказов фактическая скидка составила более 2000? #5

In [ ]:
#по данным из файла Order_details
Сначала рассчитайте для каждой строки датафрейма df_od фактическую скидку и чистую выручку.
Затем посчитайте фактическую скидку и чистую выручку по каждому заказу OrderID. Найдите заказ с самой высокой чистой выручкой. Какой OrderID у заказа? 10865